### ISSUE TITLE
Separate module

### ISSUE THREAD

**Issue by l3r8yJ** [volodya-lombrozo/test-naming-conventions#63]
@volodya-lombrozo While solving [this](https://github.com/volodya-lombrozo/test-naming-conventions/issues/56) I created [this](https://github.com/l3r8yJ/sa-tan), as you can see it contains the same base of interfaces as your plugin. What do you think about extracting the interfaces into a separate maven project to reuse as a separate library to create static analysis plugins. Where you would just need to add a few of your own rules and your new plugin would be ready. But that would require working out a more abstract architecture or something. What do you think?

**Comment by l3r8yJ** [comment]
for example 
```java

interface Rule {/**/}

interface ClassRule {/**/}

interface MethodRule {/**/}

interface ClassMemberRule {/**/}
```

or smth like that

**Comment by volodya-lombrozo** [comment]
Hello @l3r8yJ, thank you for your insightful observation! It is true that in the future, we may be able to provide a refactoring solution if we have more than two tools that share common interfaces. However, for now, I find it much easier to continue developing both plugins separately without intersection. This is mainly due to two reasons:

1. Introducing one more library with interfaces would significantly increase the complexity of deployment and integration (for both plugins).
2. The 'test-naming-conventions' project is still relatively new and its interfaces are not yet stable. It is possible that they may change further and quite often.

Thank you for your understanding and please let us know if you have any further questions or concerns.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo got it, thanks!
